name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Build Web to APK
        uses: kp-builds/website-to-apk@v1.1
        with:
          app_name: "Mark Labs"
          website_url: "."
          output_name: "MarkLabs.apk"
          
