name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Website to APK
        uses: darkshredder/website-to-apk-action@v1.1.0
        with:
          app-name: "Mark Labs"
          build-folder-path: "."
